# Generated by Django 4.2.7 on 2023-11-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20231031_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='challenge_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='challenge_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
